export default {
  LOGIN: "Login",

  REGISTER: "Register",
  REGISTER_WEB: "REGISTER_WEB",
  FORGOT_PASSWORD_WEB: "FORGOT_PASSWORD",
  FORGOT_PASSWORD: "Forgot Password",

  HOME: "Home",
  HOME_WEB: "HOME_WEB",
  HOME_TAB: "Home Tab",
  HOME_DRAWER: "Home Drawer",

  NOTIFICATIONS: "Notifications",
  NOTIFICATIONS_DRAWER: "Notifications Drawer",

  PROJECTS: "Projects",
  PROJECTS_WEB: "PROJECTS_WEB",

  CALENDAR_WEB: "CALENDAR_WEB",

  SETTINGS: "Settings",
  SETTINGS_WEB: "SETTINGS_WEB",
  ACCOUNT_SETTINGS: "Account Settings",
  SETTINGS_NAVIGATOR: "Settings Navigator",

  SETTINGS_DETAIL: "Settings Detail",
  PROFILE: "My Profile",

  CHAT: "Chat",
  ADD_CHAT: "ADD_CHAT",
  CHATTING_SCREEN: "CHATTING_SCREEN",
  CHAT_WEB: "CHAT_WEB",
  SEARCH: "SEARCH",

  CREATE_WORKSPACE: "Create workspace",
  ADD_PARTICIPANTS: "ADD_PARTICIPANTS",
  ADD_PARTICIPANTS_PROJECT_LIST: "ADD_PARTICIPANTS_PROJECT_LIST",
  CREATE_PROJECT_LIST: "Create project list",
  EDIT_PROJECT_LIST: "Edit project list",
  EDIT_PROJECT_LIST_AFTER_CREATION: "EDIT_PROJECT_LIST_AFTER_CREATION",
  EDIT_WORKSPACE: "Edit workspace",
  WORKSPACE: "WORKSPACE",
  WORKSPACE_DETAILS: "WORKSPACE_DETAILS",
  WORKSPACE_WEB: "WORKSPACE_WEB",
  ADD_PARTICIPANTS_PROJECT_LIST_AFTER_CREATION:
    "ADD_PARTICIPANTS_PROJECT_LIST_AFTER_CREATION",

  CREATE_TASK_CARD: "CREATE_TASK_CARD",
  EDIT_TASK_CARD: "EDIT_TASK_CARD",
  CREATE_SUB_TASK_CARD: "CREATE_SUB_TASK_CARD",
  EDIT_SUB_TASK_CARD: "EDIT_SUB_TASK_CARD",
  TASK_CARD: "TASK_CARD",

  COMING_SOON: "COMING_SOON",

  TODAY_DAILY_DETAILS: "TODAY_DAILY_DETAILS",

  QUICK_CREATE_TASK: "QUICK_CREATE_TASK",

  //for mobile settings
  MY_PROJECT_SCREEN: "MY_PROJECT_SCREEN",
  JOIN_A_TEAM: "JOIN_A_TEAM",
  MY_TASKS: "MY_TASKS",
  SETTINGS_SCREEN: "SETTINGS_SCREEN",
  EDIT_PROFILE: "EDIT_PROFILE",

  PROFILE_SCREEN_WEB: "ProfileScreenWeb",
};
