import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { Suspense } from "react";
import Sidebar from "@/components/Sidebar";
import { Skeleton } from "@/components/ui/skeleton";
import Navbar from "@/components/Navbar";
import WorkspaceNavbar from "@/components/WorkspaceNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Squadflow app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { workspaceId: string };
}) {
  return (
    <>
      <Sidebar />
      <div className="w-5/6 float-right p-4">{children}</div>
    </>
  );
}
