import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { Suspense } from "react";
import Sidebar from "@/components/Sidebar";
import { Skeleton } from "@/components/ui/skeleton";
import Navbar from "@/components/Navbar";
import { jwtVerify } from "jose";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { isJWTTokenExpired, verifyJWTToken } from "@/lib/helper/route.helper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Squadflow",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies().get("jwt");
  if (!cookie?.value || cookie?.value === "") redirect("/auth");

  if (!cookie || !cookie.value) {
    // Redirect to the authentication route if the JWT token is missing or empty
    redirect("/auth");
  } else {
    try {
      // Verify the JWT token
      await verifyJWTToken(cookie.value);
    } catch (error) {
      console.error("Error verifying JWT token:", error);
      redirect("/auth");
    }
  }
  return (
    <div className="h-screen">
      <Sidebar />
      <div className="h-full w-5/6 float-right px-4">{children}</div>
    </div>
  );
}
