import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { Suspense } from "react";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Squadflow",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen">
      <Sidebar />
      <div className="h-full w-full lg:w-5/6 float-right px-4">{children}</div>
      <Toaster />
    </div>
  );
}
