import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ReactQueryProvider } from "@/app/Provider";
import { ReactQueryDevtools } from "react-query/devtools";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen bg-[#F2F0EB]">
        <ReactQueryProvider>
          {children}
          {/*<ReactQueryDevtools initialIsOpen={true} />*/}
        </ReactQueryProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
